language: r
sudo: false
cache: packages
env:
  matrix:
  - LINTR_COMMENT_BOT=false secure: cT6mg+sAeAl+zV8crTIeweOvo3KI75d/H7Pb7ToMzlkwrVhrGNzHGOeWIUjFCK7yHSCm5cQwiwF59VugCBz/7kgjwdUc9Jm+Xew1A8w0qv8Y4q3bGIXgOljPd3aQaxyBO1Dm8mosJDVBJZqrjJ/GcTHDjGHZP6rH+tKJyvot05H6ZePPmosqZ7lpkA8j1lOaVFoYUaokE4RjyS3SHXYllpEEmlYHVLsnQ1DmmkaEAs1Y2bojFb7OGLfxCrDTXJHu2QZ9NIfexuXSF721vEEsQ+hSo8R9VuFye5cQvd5K0D0soj9s1sQauJM1JqrPgjN1c2w8bckfbvBSDfEBH95ssk8vxthEAMq8o8VH+TEabISlzgX7nnsTGb4kbEykFh8H2CesK/365eze8qyWrxQRsdkka+DpuMtESMLGZaeXZgf7mNZo0X9wL7hK3THc1+lEFNN5ZGcuV6j+HrQfG2DKQPjAtkqIcSt8UC3ajYDpxum77b4MLqMJGfavLjGU/ZBZ/lrizf0vJV2s4swO5XNGwTD/4V40JU4MrFu5AVYBeJUw7Fdq76jKyCAmkfdN/dPKXe3soQ1CmIWJiRwPDQ55+Ye6MXzh6n/vDdfg9Qlp69QpECfyqRN35RovfCD2SNOLxUleCW1J+Qh2gJEewgAkkIu8RJA/vIJqvml+MNq6cyM=
r:
- oldrel
- release
- devel
matrix:
  allow_failures:
  - r: devel
after_success:
- travis_wait 30 Rscript -e 'covr::codecov()'
